# This script will load, and organize the pavlovia data. Then, computes measures of interest.
# For each participant, a single, new, organized csv file that has all the necessary information will be generated.
# Author: Kianoosh Hosseini at NDCLab @FIU (https://Kianoosh.info; https://NDClab.com)
# Last Update: 2023-05-30 (YYYY-MM-DD)

library(tidyverse)
library(dplyr)
library(stringr)
library(psycho) # to compute d' measures, etc.

#Working directory should be the Psychopy experiment directory.
proje_wd <- "/Users/kihossei/Documents/GitHub/memory-for-error-mini/materials/mini_mfe"
setwd(proje_wd)

input_raw_path <- paste(proje_wd, "data", sep ="/", collapse = NULL) # input data directory
input_organized_path <- paste(proje_wd, "csv_output", sep ="/", collapse = NULL) # input directory for data files generated by the organizer script!
output_path <- paste(proje_wd, "stat_output", sep ="/", collapse = NULL) # output directory
proc_fileName <- "processed_data_mini_mfe_Proj_for_friendly.csv" # output filename
flanker_csv_fileName <- "_mini_mfe_flankerDat.csv" # each output csv file will have this on its filename
surprise_csv_fileName <- "_mini_mfe_surpriseDat.csv" # each output csv file will have this on its filename


## creating a list of all raw data csv files in the input folder.
raw_datafiles_list <- c() # an empty list that will be filled in the next "for" loop!
csvSelect <- list.files(input_raw_path, pattern = ".csv") # listing only csv files
for (i in 1:length(csvSelect)){
  temp_for_file <- ifelse (str_detect(csvSelect[i], "face_flanker_v1", negate = FALSE), 1, 0)
  if (temp_for_file == 1){
    temp_list <- csvSelect[i]
    raw_datafiles_list <- c(raw_datafiles_list, temp_list)
  }
}
# Creating the main empty dataframe that will be filled with the data from the loop below:
main_df <- setNames(data.frame(matrix(ncol = 31, nrow = 0)), c("participant_id", "congAcc", "incongAcc",
                                                               "incongruent_dat_meanRT", "errorDat_meanRT", "congruent_dat_meanRT", "corrDat_meanRT",
                                                               "congCorr_meanRT", "incongCorr_meanRT", "congCorr_logMeanRT",
                                                               "congErr_meanRT", "incongErr_meanRT", "congErr_logMeanRT", "incongErr_logMeanRT",
                                                               "incongCorr_logMeanRT", "flankEff_meanACC", "flankEff_meanRT", "flankEff_logMeanRT",
                                                               "reported_errors", "committed_errors", "memoryBias_score",
                                                               "percent_post_errorFaces_reported_friendly",
                                                               "percent_post_correctFaces_reported_friendly", "percent_pre_errorFaces_reported_friendly",
                                                               "percent_pre_correctFaces_reported_friendly", "percent_incong_correctFaces_reported_friendly",
                                                               "percent_incong_errorFaces_reported_friendly", "current_trial_diff_friendly", "post_trial_diff_friendly", "pre_trial_diff_friendly", "num_post_error_faces"))

# Counters for the number of excluded people based on each criterion
num_of_participants_removed_based_on_memory_friendly_trial_removal <- 0 # Will be updated in the loop below
num_of_participants_removed_based_on_accuracy <- 0 # Will be updated in the loop below
num_of_participants_removed_based_on_incong_error_num <- 0 # Will be updated in the loop below
num_participants_removed_based_on_num_incong_error_faces_in_friendly <- 0 # Will be updated in the loop below

# Looping over all participants
for (subject in 1:length(raw_datafiles_list)){
  #for this participant, find the raw csv file
  psychopy_file <- paste(input_raw_path,raw_datafiles_list[subject], sep = "/", collapse = NULL)

  #read in the data for this participant, establish id, and remove extraneous variables
  psychopyDat <- read.csv(file = psychopy_file, stringsAsFactors = FALSE, na.strings=c("", "NA"))
  participant_id <- psychopyDat$id[1]

  # Load this participant's flanker and surprise data frames
  flanker_name <- paste0(participant_id, flanker_csv_fileName, sep = "", collapse = NULL)
  surprise_name <- paste0(participant_id, surprise_csv_fileName, sep = "", collapse = NULL)
  flanker_df <- read.csv(file = paste(input_organized_path, flanker_name, sep = "/", collapse = NULL), stringsAsFactors = FALSE, na.strings=c("", "NA"))
  surprise_df <- read.csv(file = paste(input_organized_path, surprise_name, sep = "/", collapse = NULL), stringsAsFactors = FALSE, na.strings=c("", "NA"))

  # removing participants based on whether they just pressed the keys without actually paying attention to the task.
  # We check this by "keep_surp_memory_trial_based_on_rt" and "keep_surp_friendly_trial_based_on_rt" variables
  # in the surprise_df data frame. O means that they have responded faster than 200 ms during the given trial
  # and therefore, we need to remove that surprise trial.
  # In this study, we will remove people based on the surprise memory task not surprise friendly task.
  # If more than 20% of surprise trials are removed, we exclude that participant.
  number_of_removed_trials_in_the_friendly_surp <- (nrow(surprise_df) - 80) - (sum(surprise_df$keep_surp_friendly_trial_based_on_rt, na.rm = TRUE))
  number_of_faces_in_surp_friendly_task <- nrow(surprise_df) - 80 # 80 is the number of new faces that exist in the surp_memory task but not in the surp_friendly task!
  twenty_percent_threshold <- round(0.2 * number_of_faces_in_surp_friendly_task)

  if (number_of_removed_trials_in_the_friendly_surp <= twenty_percent_threshold){ # Participants who have less than twenty_percent_threshold surprise
    # trials removed, will be included.

    # Check to see if this participant has the flanker accuracy above 60%
    if (mean(as.numeric(flanker_df$current_trial_accuracy)) >= 0.6){

      # check to see if the participant has at least 8 legit incongruent errors or not.
      incong_flankerDat <- filter(flanker_df, current_trial_congruency == 0)
      cong_flankerDat <- filter(flanker_df, current_trial_congruency == 1)
      error_incong_flankerDat <- filter(incong_flankerDat, current_trial_accuracy == 0)
      legit_error_incong_flankerDat <- filter(error_incong_flankerDat, current_trial_legitResponse == 1)
      if (nrow(legit_error_incong_flankerDat) >= 8 ){

        # Checking to see if there are at least 6 incongruent error faces in the surprise_df of this participant.
        # First we need to remove the trials that are marked based on rt!
        surprise_df <- filter(surprise_df, keep_surp_friendly_trial_based_on_rt == 1)
        num_incong_error_faces_in_surp <- 0
        # Counting the number of legit incong error faces available in surprise_df!
        for (rr in 1:nrow(legit_error_incong_flankerDat)){
          temp_face <- legit_error_incong_flankerDat$current_trial_face[rr]
          temp_for_surp <- filter(surprise_df, face == temp_face)
          errorFace_exist_in_surpDat <- ifelse(nrow(temp_for_surp) == 1, 1,0)
          if (errorFace_exist_in_surpDat == 1){
            num_incong_error_faces_in_surp <- num_incong_error_faces_in_surp + 1
          }
        } # Closing the loop that counts the number of incong error faces available in surprise_df!
        if (num_incong_error_faces_in_surp >= 8){

          incongAcc <- mean(as.numeric(incong_flankerDat$current_trial_accuracy))
          congAcc <- mean(as.numeric(cong_flankerDat$current_trial_accuracy))

          #


          # subset the data for correct and error trials, separately for congruent and incongruent trials, creating new data frames for each
          corrDat <- flanker_df[flanker_df$current_trial_accuracy == 1,]
          corrDat_meanRT <- mean(corrDat$current_trial_rt, na.rm = TRUE)

          congruent_dat <- flanker_df[flanker_df$current_trial_congruency == 1,]
          congruent_dat_meanRT <- mean(congruent_dat$current_trial_rt, na.rm = TRUE)

          cong_corrDat <- corrDat[corrDat$current_trial_congruency == 1,]
          incong_corrDat <- corrDat[corrDat$current_trial_congruency == 0,]

          errorDat <- flanker_df[flanker_df$current_trial_accuracy == 0,]
          errorDat_meanRT <- mean(errorDat$current_trial_rt, na.rm = TRUE)

          incongruent_dat <- flanker_df[flanker_df$current_trial_congruency == 0,]
          incongruent_dat_meanRT <- mean(incongruent_dat$current_trial_rt, na.rm = TRUE)


          cong_errorDat <- errorDat[errorDat$current_trial_congruency == 1,]
          incong_errorDat <- errorDat[errorDat$current_trial_congruency == 0,]
          #for correct trials, compute mean RT (raw and log-corrected)
          congCorr_meanRT <- mean(cong_corrDat$current_trial_rt, na.rm = TRUE)
          incongCorr_meanRT <- mean(incong_corrDat$current_trial_rt, na.rm = TRUE)

          congErr_meanRT <- mean(cong_errorDat$current_trial_rt, na.rm = TRUE)
          incongErr_meanRT <- mean(incong_errorDat$current_trial_rt, na.rm = TRUE)

          congCorr_logMeanRT <- mean(log((1+cong_corrDat$current_trial_rt)), na.rm = TRUE)
          incongCorr_logMeanRT <- mean(log((1+incong_corrDat$current_trial_rt)), na.rm = TRUE)

          congErr_logMeanRT <- mean(log((1+cong_errorDat$current_trial_rt)), na.rm = TRUE)
          incongErr_logMeanRT <- mean(log((1+incong_errorDat$current_trial_rt)), na.rm = TRUE)

          # compute flanker-effect scores for accuracy, RT, log-RT
          flankEff_meanACC <- incongAcc - congAcc
          flankEff_meanRT <- incongCorr_meanRT - congCorr_meanRT
          flankEff_logMeanRT <- incongCorr_logMeanRT - congCorr_logMeanRT

          #
          # number of committed errors in the flanker task
          committed_errors <- nrow(errorDat)
          # number of reported errors
          psychopyDatTrim <- psychopyDat[("textbox_2.text")] # stores the number of reported errors by subjects
          reported_errors <- subset(psychopyDatTrim, complete.cases(psychopyDatTrim$textbox_2.text))
          reported_errors <- reported_errors$textbox_2.text # number of reported errors by participants
          reported_errors <- str_extract_all(reported_errors, '\\d+\\.?\\d*') # to extract all sequences of digits from the input string
          # There was a participant who had reported 70/100. values 70 and 100. To solve this issue, I replace this kind of values with NAs!
          if (length(reported_errors) == 0){ # there is no reported errors
            reported_errors <- NA
            memoryBias_score <- NA
          } else {
            reported_errors <- parse_number(reported_errors[[1]]) # in cases like 70/100, we will have 70 100 at this stage. So, length(reported_errors) will
            # higher than 1.
            if (length(reported_errors) > 1){ # In case they have reported sth like 70/100
              reported_errors <- NA
              memoryBias_score <- NA
            } else if (length(reported_errors) == 1){
              reported_errors <- reported_errors[1]
              memoryBias_score <- ((reported_errors - committed_errors)/ reported_errors) # percent bias score calculation
            }
          }



          ### number of incong error faces identified as old
          num_incong_errorFaces_reported_unfriendly <- 0 # this is the number of incongruent error faces that they report as unfriendly and will be updated in the loop below:
          for (iii in 1:nrow(error_incong_flankerDat)){
            if (error_incong_flankerDat$current_trial_legitResponse[iii] == 1){ # if this trial is legit
              temp_face_from_flanker <- error_incong_flankerDat$current_trial_face[iii]
              temp_face_row_in_surp <- filter(surprise_df, face == temp_face_from_flanker)
              if (nrow(temp_face_row_in_surp) == 1){ # if the incong error face exist in the surprise_df
                if (temp_face_row_in_surp$identified_as_friendly == 0){ # the face is identified as unfriendly
                  num_incong_errorFaces_reported_unfriendly <- num_incong_errorFaces_reported_unfriendly + 1 # The number of incongruent error faces that they report as OLD
                }
              }
            }
          } # closing the loop over error incong flankerDat

          ### number of incong error faces identified as friendly
          num_incong_errorFaces_reported_friendly <- 0 # this is the number of incongruent error faces that they report as friendly and will be updated in the loop below:
          for (iii in 1:nrow(error_incong_flankerDat)){
            if (error_incong_flankerDat$current_trial_legitResponse[iii] == 1){ # if this trial is legit
              temp_face_from_flanker <- error_incong_flankerDat$current_trial_face[iii]
              temp_face_row_in_surp <- filter(surprise_df, face == temp_face_from_flanker)
              if (nrow(temp_face_row_in_surp) == 1){ # if old incong error face exist in the surprise_df
                if (temp_face_row_in_surp$identified_as_friendly == 1){ # the face is identified as friendly
                  num_incong_errorFaces_reported_friendly <- num_incong_errorFaces_reported_friendly + 1 # The number of incongruent error faces that they report as friendly
                }
              }
            }
          } # closing the loop over error incong flankerDat


          ### number of incong correct faces identified as unfriendly
          num_incong_correctFaces_reported_unfriendly <- 0 # this is the number of incongruent correct faces that they report as unfriendly and will be updated in the loop below:
          for (iii in 1:nrow(incong_corrDat)){
            if (incong_corrDat$current_trial_legitResponse[iii] == 1){ # if this trial is legit
              temp_face_from_flanker <- incong_corrDat$current_trial_face[iii]
              temp_face_row_in_surp <- filter(surprise_df, face == temp_face_from_flanker)
              if (nrow(temp_face_row_in_surp) == 1){ # if old incong correct face exist in the surprise_df
                if (temp_face_row_in_surp$identified_as_friendly == 0){ # the face is identified as unfriendly
                  num_incong_correctFaces_reported_unfriendly <- num_incong_correctFaces_reported_unfriendly + 1 # The number of incongruent correct faces that they report as unfriendly
                }
              }
            }
          } # closing the loop over correct incong flankerDat

          ### number of incong correct faces identified as friendly
          num_incong_correctFaces_reported_friendly <- 0 # this is the number of incongruent correct faces that they report as friendly and will be updated in the loop below:
          for (iii in 1:nrow(incong_corrDat)){
            if (incong_corrDat$current_trial_legitResponse[iii] == 1){ # if this trial is legit
              temp_face_from_flanker <- incong_corrDat$current_trial_face[iii]
              temp_face_row_in_surp <- filter(surprise_df, face == temp_face_from_flanker)
              if (nrow(temp_face_row_in_surp) == 1){ # if old incong correct face exist in the surprise_df
                if (temp_face_row_in_surp$identified_as_friendly == 1){ # the face is identified as friendly
                  num_incong_correctFaces_reported_friendly <- num_incong_correctFaces_reported_friendly + 1 # The number of incongruent correct faces that they report as friendly
                }
              }
            }
          } # closing the loop over correct incong flankerDat
          # Pre and post trials must be correct while they can be either incongruent or congruent.
          ### number of post error faces identified as unfriendly
          num_post_errorFaces_reported_unfriendly <- 0 # this is the number of post error faces that they report as unfriendly and will be updated in the loop below:
          for (iii in 1:nrow(error_incong_flankerDat)){
            if (!is.na(error_incong_flankerDat$post_trial_legitResponse[iii])){ # In case current trial is the last trial in the block, post/pre_trial will be NA! So, this condition will prevent from errors!
              if (error_incong_flankerDat$post_trial_legitResponse[iii] == 1){ # if this trial is legit
                if (error_incong_flankerDat$post_trial_accuracy[iii] == 1){ #Pre and post trials must be correct while they can be either incongruent or congruent.
                  temp_face_from_flanker <- error_incong_flankerDat$post_trial_face[iii]
                  temp_face_row_in_surp <- filter(surprise_df, face == temp_face_from_flanker)
                  if (nrow(temp_face_row_in_surp) == 1){ # if old incong error face exist in the surprise_df
                    if (temp_face_row_in_surp$identified_as_friendly == 0){ # the face is identified as unfriendly
                      num_post_errorFaces_reported_unfriendly <- num_post_errorFaces_reported_unfriendly + 1 # The number of incongruent error faces that they report as unfriendly
                    }
                  }
                }
              }
            }
          } # closing the loop


          ### number of incong post error faces identified as friendly
          num_post_errorFaces_reported_friendly <- 0 # this is the number of post error faces that they report as friendly and will be updated in the loop below:
          for (iii in 1:nrow(error_incong_flankerDat)){
            if (!is.na(error_incong_flankerDat$post_trial_legitResponse[iii])){
              if (error_incong_flankerDat$post_trial_legitResponse[iii] == 1){ # if this trial is legit
                if (error_incong_flankerDat$post_trial_accuracy[iii] == 1){ #Pre and post trials must be correct while they can be either incongruent or congruent.
                  temp_face_from_flanker <- error_incong_flankerDat$post_trial_face[iii]
                  temp_face_row_in_surp <- filter(surprise_df, face == temp_face_from_flanker)
                  if (nrow(temp_face_row_in_surp) == 1){ # if old incong error face exist in the surprise_df
                    if (temp_face_row_in_surp$identified_as_friendly == 1){ # the face is identified as friendly
                      num_post_errorFaces_reported_friendly <- num_post_errorFaces_reported_friendly + 1 # The number of incongruent error faces that they report as friendly
                    }
                  }
                }
              }
            }
          } # closing the loop

          ### number of incong post correct faces identified as unfriendly
          num_post_correctFaces_reported_unfriendly <- 0 # this is the number of post correct faces that they report as unfriendly and will be updated in the loop below:
          for (iii in 1:nrow(incong_corrDat)){
            if (!is.na(incong_corrDat$post_trial_legitResponse[iii])){
              if (incong_corrDat$post_trial_legitResponse[iii] == 1){ # if this trial is legit
                if (incong_corrDat$post_trial_accuracy[iii] == 1){ #Pre and post trials must be correct while they can be either incongruent or congruent.
                  temp_face_from_flanker <- incong_corrDat$post_trial_face[iii]
                  temp_face_row_in_surp <- filter(surprise_df, face == temp_face_from_flanker)
                  if (nrow(temp_face_row_in_surp) == 1){ # if old incong correct face exist in the surprise_df
                    if (temp_face_row_in_surp$identified_as_friendly == 0){ # the face is identified as unfriendly
                      num_post_correctFaces_reported_unfriendly <- num_post_correctFaces_reported_unfriendly + 1 # The number of incongruent correct faces that they report as unfriendly
                    }
                  }
                }
              }
            }
          } # closing the loop

          ### number of incong post correct faces identified as friendly
          num_post_correctFaces_reported_friendly <- 0 # this is the number of post correct faces that they report as New and will be updated in the loop below:
          for (iii in 1:nrow(incong_corrDat)){
            if (!is.na(incong_corrDat$post_trial_legitResponse[iii])){
              if (incong_corrDat$post_trial_legitResponse[iii] == 1){ # if this trial is legit
                if (incong_corrDat$post_trial_accuracy[iii] == 1){ #Pre and post trials must be correct while they can be either incongruent or congruent.
                  temp_face_from_flanker <- incong_corrDat$post_trial_face[iii]
                  temp_face_row_in_surp <- filter(surprise_df, face == temp_face_from_flanker)
                  if (nrow(temp_face_row_in_surp) == 1){ # if old incong correct face exist in the surprise_df
                    if (temp_face_row_in_surp$identified_as_friendly == 1){ # the face is identified as friendly
                      num_post_correctFaces_reported_friendly <- num_post_correctFaces_reported_friendly + 1 # The number of incongruent correct faces that they report as friendly
                    }
                  }
                }
              }
            }
          } # closing the loop

          ### number of incong pre error faces identified as old
          num_pre_errorFaces_reported_unfriendly <- 0 # this is the number of pre error faces that they report as OLD and will be updated in the loop below:
          for (iii in 1:nrow(error_incong_flankerDat)){
            if (!is.na(error_incong_flankerDat$pre_trial_legitResponse[iii])){
              if (error_incong_flankerDat$pre_trial_legitResponse[iii] == 1){ # if this trial is legit
                if (error_incong_flankerDat$pre_trial_accuracy[iii] == 1){ #Pre and post trials must be correct while they can be either incongruent or congruent.
                  temp_face_from_flanker <- error_incong_flankerDat$pre_trial_face[iii]
                  temp_face_row_in_surp <- filter(surprise_df, face == temp_face_from_flanker)
                  if (nrow(temp_face_row_in_surp) == 1){ # if old incong error face exist in the surprise_df
                    if (temp_face_row_in_surp$identified_as_friendly == 0){ # the face is identified as unfriendly
                      num_pre_errorFaces_reported_unfriendly <- num_pre_errorFaces_reported_unfriendly + 1 # The number of incongruent error faces that they report as unfriendly
                    }
                  }
                }
              }
            }
          } # closing the loop

          ### number of incong pre error faces identified as friendly
          num_pre_errorFaces_reported_friendly <- 0 # this is the number of pre error faces that they report as New and will be updated in the loop below:
          for (iii in 1:nrow(error_incong_flankerDat)){
            if (!is.na(error_incong_flankerDat$pre_trial_legitResponse[iii])){
              if (error_incong_flankerDat$pre_trial_legitResponse[iii] == 1){ # if this trial is legit
                if (error_incong_flankerDat$pre_trial_accuracy[iii] == 1){ #Pre and post trials must be correct while they can be either incongruent or congruent.
                  temp_face_from_flanker <- error_incong_flankerDat$pre_trial_face[iii]
                  temp_face_row_in_surp <- filter(surprise_df, face == temp_face_from_flanker)
                  if (nrow(temp_face_row_in_surp) == 1){ # if old incong error face exist in the surprise_df
                    if (temp_face_row_in_surp$identified_as_friendly == 1){ # the face is identified as friendly
                      num_pre_errorFaces_reported_friendly <- num_pre_errorFaces_reported_friendly + 1 # The number of incongruent error faces that they report as friendly
                    }
                  }
                }
              }
            }
          } # closing the loop


          ### number of incong pre correct faces identified as unfriendly
          num_pre_correctFaces_reported_unfriendly <- 0 # this is the number of pre correct faces that they report as OLD and will be updated in the loop below:
          for (iii in 1:nrow(incong_corrDat)){
            if (!is.na(incong_corrDat$pre_trial_legitResponse[iii])){
              if (incong_corrDat$pre_trial_legitResponse[iii] == 1){ # if this trial is legit
                if (incong_corrDat$pre_trial_accuracy[iii] == 1){ #Pre and post trials must be correct while they can be either incongruent or congruent.
                  temp_face_from_flanker <- incong_corrDat$pre_trial_face[iii]
                  temp_face_row_in_surp <- filter(surprise_df, face == temp_face_from_flanker)
                  if (nrow(temp_face_row_in_surp) == 1){ # if old incong correct face exist in the surprise_df
                    if (temp_face_row_in_surp$identified_as_friendly == 0){ # the face is identified as unfriendly
                      num_pre_correctFaces_reported_unfriendly <- num_pre_correctFaces_reported_unfriendly + 1 # The number of incongruent correct faces that they report as unfriendly
                    }
                  }
                }
              }
            }
          } # closing the loop


          ### number of incong pre correct faces identified as friendly
          num_pre_correctFaces_reported_friendly <- 0 # this is the number of pre correct faces that they report as friendly and will be updated in the loop below:
          for (iii in 1:nrow(incong_corrDat)){
            if (!is.na(incong_corrDat$pre_trial_legitResponse[iii])){
              if (incong_corrDat$pre_trial_legitResponse[iii] == 1){ # if this trial is legit
                if (incong_corrDat$pre_trial_accuracy[iii] == 1){ #Pre and post trials must be correct while they can be either incongruent or congruent.
                  temp_face_from_flanker <- incong_corrDat$pre_trial_face[iii]
                  temp_face_row_in_surp <- filter(surprise_df, face == temp_face_from_flanker)
                  if (nrow(temp_face_row_in_surp) == 1){ # if old incong correct face exist in the surprise_df
                    if (temp_face_row_in_surp$identified_as_friendly == 1){ # the face is identified as friendly
                      num_pre_correctFaces_reported_friendly <- num_pre_correctFaces_reported_friendly + 1 # The number of incongruent correct faces that they report as friendly
                    }
                  }
                }
              }
            }
          } # closing the loop

          ########################## Friendliness Percentage ########################################

          ###########################################################################################

          # num_incong_errorFaces_reported_friendly
          percent_incong_errorFaces_reported_friendly <- (num_incong_errorFaces_reported_friendly/(num_incong_errorFaces_reported_unfriendly + num_incong_errorFaces_reported_friendly)) * 100

          # num_incong_correctFaces_reported_friendly
          percent_incong_correctFaces_reported_friendly <- (num_incong_correctFaces_reported_friendly/(num_incong_correctFaces_reported_unfriendly + num_incong_correctFaces_reported_friendly)) * 100

          # num_pre_correctFaces_reported_friendly
          percent_pre_correctFaces_reported_friendly <- (num_pre_correctFaces_reported_friendly/(num_pre_correctFaces_reported_unfriendly + num_pre_correctFaces_reported_friendly)) * 100

          # num_pre_errorFaces_reported_friendly
          percent_pre_errorFaces_reported_friendly <- (num_pre_errorFaces_reported_friendly/(num_pre_errorFaces_reported_unfriendly + num_pre_errorFaces_reported_friendly)) * 100

          # num_post_correctFaces_reported_friendly
          percent_post_correctFaces_reported_friendly <- (num_post_correctFaces_reported_friendly/(num_post_correctFaces_reported_unfriendly + num_post_correctFaces_reported_friendly)) * 100

          # num_post_errorFaces_reported_friendly
          percent_post_errorFaces_reported_friendly <- (num_post_errorFaces_reported_friendly/(num_post_errorFaces_reported_unfriendly + num_post_errorFaces_reported_friendly)) * 100

          # difference scores
          current_trial_diff_friendly <- percent_incong_errorFaces_reported_friendly - percent_incong_correctFaces_reported_friendly

          post_trial_diff_friendly <- percent_post_errorFaces_reported_friendly - percent_post_correctFaces_reported_friendly

          pre_trial_diff_friendly <- percent_pre_errorFaces_reported_friendly - percent_pre_correctFaces_reported_friendly

          # For later, we need to have the following value in main_df:
          num_post_error_faces <- 0
          for (rr in 1:nrow(legit_error_incong_flankerDat)){
            temp_face <- legit_error_incong_flankerDat$post_trial_face[rr] # select post-error faces
            temp_for_surp <- filter(surprise_df, face == temp_face)
            errorFace_exist_in_surpDat <- ifelse(nrow(temp_for_surp) == 1, 1,0)
            if (errorFace_exist_in_surpDat == 1){
              num_post_error_faces <- num_post_error_faces + 1
            }
          } # Closing the loop that counts the number of num_post_error_faces available in surprise_df!

          #### filling the main data frame
          main_df[nrow(main_df) + 1,] <-c(participant_id, congAcc, incongAcc,
                                          incongruent_dat_meanRT, errorDat_meanRT, congruent_dat_meanRT, corrDat_meanRT,
                                          congCorr_meanRT, incongCorr_meanRT, congCorr_logMeanRT,
                                          congErr_meanRT, incongErr_meanRT, congErr_logMeanRT, incongErr_logMeanRT,
                                          incongCorr_logMeanRT, flankEff_meanACC, flankEff_meanRT, flankEff_logMeanRT,
                                          reported_errors, committed_errors, memoryBias_score, percent_post_errorFaces_reported_friendly,
                                          percent_post_correctFaces_reported_friendly, percent_pre_errorFaces_reported_friendly,
                                          percent_pre_correctFaces_reported_friendly, percent_incong_correctFaces_reported_friendly,
                                          percent_incong_errorFaces_reported_friendly, current_trial_diff_friendly, post_trial_diff_friendly, pre_trial_diff_friendly,  num_post_error_faces)


        } else { # If a participant has been excluded because they had less than 8 legit incong error faces in the surprise memory task, we add 1 to the counter below.
          num_participants_removed_based_on_num_incong_error_faces_in_friendly <- num_participants_removed_based_on_num_incong_error_faces_in_friendly + 1
        }
      } else { # If a participant has been excluded because they had less than 8 legit incong errors, we add 1 to the counter below.
        num_of_participants_removed_based_on_incong_error_num <- num_of_participants_removed_based_on_incong_error_num + 1
      }
    } else { # If a participant has been excluded because they had less than 60% flanker accuracy, we add 1 to the counter below.
      num_of_participants_removed_based_on_accuracy <- num_of_participants_removed_based_on_accuracy + 1
    }
  } else { # If a participant has been excluded because they had more than 20% surp trial removed, we add 1 to the counter below.
    num_of_participants_removed_based_on_memory_friendly_trial_removal <- num_of_participants_removed_based_on_memory_friendly_trial_removal + 1
  }
} # Closing the loop for each participant


### Loading RedCap questionnaire data
redcapDat <- read.csv(file = "/Users/kihossei/OneDrive - Florida International University/Projects/Memory_for_error/redcap_data_from_sfe/202203v0socialflanke_SCRD_2022-09-23_1133.csv")

# Keeping the columns that we need!
redcapDat <- redcapDat[c("record_id", "demo_c_yob_s1_r1_e1", "scaared_b_scrdSoc_s1_r1_e1", "scaared_b_scrdGA_s1_r1_e1", "scaared_b_scrdTotal_s1_r1_e1", "bfne_b_scrdTotal_s1_r1_e1")]

# adding new columns to the "percent_mainDat" dataframe from redcapDat
for (rr in 1:nrow(main_df)){
  temp_id <- main_df$participant_id[rr]
  tempDat <- filter(redcapDat, record_id == temp_id)
  if (nrow(tempDat) == 1){
    main_df$scaared_b_scrdSoc_s1_r1_e1[rr] <- tempDat$scaared_b_scrdSoc_s1_r1_e1
    main_df$scaared_b_scrdGA_s1_r1_e1[rr] <- tempDat$scaared_b_scrdGA_s1_r1_e1
    main_df$scaared_b_scrdTotal_s1_r1_e1[rr] <- tempDat$scaared_b_scrdTotal_s1_r1_e1
    main_df$bfne_b_scrdTotal_s1_r1_e1[rr] <- tempDat$bfne_b_scrdTotal_s1_r1_e1
    main_df$demo_c_yob_s1_r1_e1[rr] <- tempDat$demo_c_yob_s1_r1_e1
  } else if (nrow(tempDat) == 0){
    main_df$scaared_b_scrdSoc_s1_r1_e1[rr] <- NA
    main_df$scaared_b_scrdGA_s1_r1_e1[rr] <- NA
    main_df$scaared_b_scrdTotal_s1_r1_e1[rr] <- NA
    main_df$bfne_b_scrdTotal_s1_r1_e1[rr] <- NA
    main_df$demo_c_yob_s1_r1_e1[rr] <- NA
  }
}


### Loading EEG ERP data
eeg_ern <- read.csv(file = "/Users/kihossei/Documents/GitHub/memory-for-error-mini/derivatives/eeg/eeg_erp_output/mini_mfe_erpDat_ern_compMeans.csv")

# Keeping the columns that we need!
eeg_ern <- eeg_ern[c("id", "ERN", "CRN", "deltaERN")]

# adding new columns to the "percent_mainDat" dataframe from eeg_erp
for (rr in 1:nrow(main_df)){
  temp_id <- main_df$participant_id[rr]
  tempDat <- filter(eeg_ern, id == temp_id)
  if (nrow(tempDat) == 1){
    main_df$ERN[rr] <- tempDat$ERN
    main_df$CRN[rr] <- tempDat$CRN
    main_df$deltaERN[rr] <- tempDat$deltaERN
  } else if (nrow(tempDat) == 0){
    main_df$ERN[rr] <- NA
    main_df$CRN[rr] <- NA
    main_df$deltaERN[rr] <- NA
  }
}

### Loading EEG ERP data
eeg_pea1 <- read.csv(file = "/Users/kihossei/Documents/GitHub/memory-for-error-mini/derivatives/eeg/eeg_erp_output/mini_mfe_erpDat_PEA1_compMeans.csv")

# Keeping the columns that we need!
eeg_pea1 <- eeg_pea1[c("id", "PE_error", "PE_correct", "deltaPE")]

# adding new columns to the "percent_mainDat" dataframe from eeg_erp
for (rr in 1:nrow(main_df)){
  temp_id <- main_df$participant_id[rr]
  tempDat <- filter(eeg_pea1, id == temp_id)
  if (nrow(tempDat) == 1){
    main_df$PEA1_error[rr] <- tempDat$PE_error
    main_df$PEA1_correct[rr] <- tempDat$PE_correct
    main_df$deltaPEA1[rr] <- tempDat$deltaPE
  } else if (nrow(tempDat) == 0){
    main_df$PEA1_error[rr] <- NA
    main_df$PEA1_correct[rr] <- NA
    main_df$deltaPEA1[rr] <- NA
  }
}

### Loading EEG ERP data
eeg_pea2 <- read.csv(file = "/Users/kihossei/Documents/GitHub/memory-for-error-mini/derivatives/eeg/eeg_erp_output/mini_mfe_erpDat_PEA2_compMeans.csv")

# Keeping the columns that we need!
eeg_pea2 <- eeg_pea2[c("id", "PE_error", "PE_correct", "deltaPE")]

# adding new columns to the "percent_mainDat" dataframe from eeg_erp
for (rr in 1:nrow(main_df)){
  temp_id <- main_df$participant_id[rr]
  tempDat <- filter(eeg_pea2, id == temp_id)
  if (nrow(tempDat) == 1){
    main_df$PEA2_error[rr] <- tempDat$PE_error
    main_df$PEA2_correct[rr] <- tempDat$PE_correct
    main_df$deltaPEA2[rr] <- tempDat$deltaPE
  } else if (nrow(tempDat) == 0){
    main_df$PEA2_error[rr] <- NA
    main_df$PEA2_correct[rr] <- NA
    main_df$deltaPEA2[rr] <- NA
  }
}

### Loading EEG ERP data
eeg_peb2 <- read.csv(file = "/Users/kihossei/Documents/GitHub/memory-for-error-mini/derivatives/eeg/eeg_erp_output/mini_mfe_erpDat_PEB2_compMeans.csv")

# Keeping the columns that we need!
eeg_peb2 <- eeg_peb2[c("id", "PE_error", "PE_correct", "deltaPE")]

# adding new columns to the "percent_mainDat" dataframe from eeg_erp
for (rr in 1:nrow(main_df)){
  temp_id <- main_df$participant_id[rr]
  tempDat <- filter(eeg_peb2, id == temp_id)
  if (nrow(tempDat) == 1){
    main_df$PEB2_error[rr] <- tempDat$PE_error
    main_df$PEB2_correct[rr] <- tempDat$PE_correct
    main_df$deltaPEB2[rr] <- tempDat$deltaPE
  } else if (nrow(tempDat) == 0){
    main_df$PEB2_error[rr] <- NA
    main_df$PEB2_correct[rr] <- NA
    main_df$deltaPEB2[rr] <- NA
  }
}

### Loading EEG ERP data
eeg_peb3 <- read.csv(file = "/Users/kihossei/Documents/GitHub/memory-for-error-mini/derivatives/eeg/eeg_erp_output/mini_mfe_erpDat_PEB3_compMeans.csv")

# Keeping the columns that we need!
eeg_peb3 <- eeg_peb3[c("id", "PE_error", "PE_correct", "deltaPE")]

# adding new columns to the "percent_mainDat" dataframe from eeg_erp
for (rr in 1:nrow(main_df)){
  temp_id <- main_df$participant_id[rr]
  tempDat <- filter(eeg_peb3, id == temp_id)
  if (nrow(tempDat) == 1){
    main_df$PEB3_error[rr] <- tempDat$PE_error
    main_df$PEB3_correct[rr] <- tempDat$PE_correct
    main_df$deltaPEB3[rr] <- tempDat$deltaPE
  } else if (nrow(tempDat) == 0){
    main_df$PEB3_error[rr] <- NA
    main_df$PEB3_correct[rr] <- NA
    main_df$deltaPEB3[rr] <- NA
  }
}

### Loading EEG theta power data
eeg_theta_power <- read.csv(file = "/Users/kihossei/Documents/GitHub/memory-for-error-mini/derivatives/eeg/TF_outputs/csv_for_stat/theta_power.csv")

# Keeping the columns that we need!
eeg_theta_power <- eeg_theta_power[c("id", "incong_error_theta_power", "incong_correct_theta_power", "difference_score")]

# adding new columns to the "percent_mainDat" dataframe from eeg_erp
for (rr in 1:nrow(main_df)){
  temp_id <- main_df$participant_id[rr]
  tempDat <- filter(eeg_theta_power, id == temp_id)
  if (nrow(tempDat) == 1){
    main_df$incong_error_theta_power[rr] <- tempDat$incong_error_theta_power
    main_df$incong_correct_theta_power[rr] <- tempDat$incong_correct_theta_power
    main_df$theta_power_difference_score[rr] <- tempDat$difference_score
  } else if (nrow(tempDat) == 0){
    main_df$incong_error_theta_power[rr] <- NA
    main_df$incong_correct_theta_power[rr] <- NA
    main_df$theta_power_difference_score[rr] <- NA
  }
}

### Loading EEG beta power data
eeg_beta_power_500 <- read.csv(file = "/Users/kihossei/Documents/GitHub/memory-for-error-mini/derivatives/eeg/TF_outputs/csv_for_stat/beta500/theta_power.csv")

# Keeping the columns that we need!
eeg_beta_power_500 <- eeg_beta_power_500[c("id", "incong_error_theta_power", "incong_correct_theta_power", "difference_score")]

# adding new columns to the "main_df" dataframe from eeg_erp
for (rr in 1:nrow(main_df)){
  temp_id <- main_df$participant_id[rr]
  tempDat <- filter(eeg_beta_power_500, id == temp_id)
  if (nrow(tempDat) == 1){
    main_df$incong_error_beta_power500[rr] <- tempDat$incong_error_theta_power
    main_df$incong_correct_beta_power500[rr] <- tempDat$incong_correct_theta_power
    main_df$beta_power_difference_score500[rr] <- tempDat$difference_score
  } else if (nrow(tempDat) == 0){
    main_df$incong_error_beta_power500[rr] <- NA
    main_df$incong_correct_beta_power500[rr] <- NA
    main_df$beta_power_difference_score500[rr] <- NA
  }
}

### Loading EEG beta power data
eeg_beta_power_1000 <- read.csv(file = "/Users/kihossei/Documents/GitHub/memory-for-error-mini/derivatives/eeg/TF_outputs/csv_for_stat/beta1000/theta_power.csv")

# Keeping the columns that we need!
eeg_beta_power_1000 <- eeg_beta_power_1000[c("id", "incong_error_theta_power", "incong_correct_theta_power", "difference_score")]

# adding new columns to the "main_df" dataframe from eeg_erp
for (rr in 1:nrow(main_df)){
  temp_id <- main_df$participant_id[rr]
  tempDat <- filter(eeg_beta_power_1000, id == temp_id)
  if (nrow(tempDat) == 1){
    main_df$incong_error_beta_power1000[rr] <- tempDat$incong_error_theta_power
    main_df$incong_correct_beta_power1000[rr] <- tempDat$incong_correct_theta_power
    main_df$beta_power_difference_score1000[rr] <- tempDat$difference_score
  } else if (nrow(tempDat) == 0){
    main_df$incong_error_beta_power1000[rr] <- NA
    main_df$incong_correct_beta_power1000[rr] <- NA
    main_df$beta_power_difference_score1000[rr] <- NA
  }
}

### Loading EEG beta power data
eeg_beta_power_1500 <- read.csv(file = "/Users/kihossei/Documents/GitHub/memory-for-error-mini/derivatives/eeg/TF_outputs/csv_for_stat/beta1500/theta_power.csv")

# Keeping the columns that we need!
eeg_beta_power_1500 <- eeg_beta_power_1500[c("id", "incong_error_theta_power", "incong_correct_theta_power", "difference_score")]

# adding new columns to the "main_df" dataframe from eeg_erp
for (rr in 1:nrow(main_df)){
  temp_id <- main_df$participant_id[rr]
  tempDat <- filter(eeg_beta_power_1500, id == temp_id)
  if (nrow(tempDat) == 1){
    main_df$incong_error_beta_power1500[rr] <- tempDat$incong_error_theta_power
    main_df$incong_correct_beta_power1500[rr] <- tempDat$incong_correct_theta_power
    main_df$beta_power_difference_score1500[rr] <- tempDat$difference_score
  } else if (nrow(tempDat) == 0){
    main_df$incong_error_beta_power1500[rr] <- NA
    main_df$incong_correct_beta_power1500[rr] <- NA
    main_df$beta_power_difference_score1500[rr] <- NA
  }
}

### Loading EEG beta power data
eeg_beta_power_2000 <- read.csv(file = "/Users/kihossei/Documents/GitHub/memory-for-error-mini/derivatives/eeg/TF_outputs/csv_for_stat/beta2000/theta_power.csv")

# Keeping the columns that we need!
eeg_beta_power_2000 <- eeg_beta_power_2000[c("id", "incong_error_theta_power", "incong_correct_theta_power", "difference_score")]

# adding new columns to the "main_df" dataframe from eeg_erp
for (rr in 1:nrow(main_df)){
  temp_id <- main_df$participant_id[rr]
  tempDat <- filter(eeg_beta_power_2000, id == temp_id)
  if (nrow(tempDat) == 1){
    main_df$incong_error_beta_power2000[rr] <- tempDat$incong_error_theta_power
    main_df$incong_correct_beta_power2000[rr] <- tempDat$incong_correct_theta_power
    main_df$beta_power_difference_score2000[rr] <- tempDat$difference_score
  } else if (nrow(tempDat) == 0){
    main_df$incong_error_beta_power2000[rr] <- NA
    main_df$incong_correct_beta_power2000[rr] <- NA
    main_df$beta_power_difference_score2000[rr] <- NA
  }
}


### Loading EEG TF ITPS data
eeg_ITPS <- read.csv(file = "/Users/kihossei/Documents/GitHub/memory-for-error-mini/derivatives/eeg/TF_outputs/csv_for_stat/ITPS.csv")

# Keeping the columns that we need!
eeg_ITPS <- eeg_ITPS[c("id", "incong_error_ITPS", "incong_correct_ITPS", "difference_score")]

# adding new columns to the "percent_mainDat" dataframe from eeg_erp
for (rr in 1:nrow(main_df)){
  temp_id <- main_df$participant_id[rr]
  tempDat <- filter(eeg_ITPS, id == temp_id)
  if (nrow(tempDat) == 1){
    main_df$incong_error_ITPS[rr] <- tempDat$incong_error_ITPS
    main_df$incong_correct_ITPS[rr] <- tempDat$incong_correct_ITPS
    main_df$ITPS_difference_score[rr] <- tempDat$difference_score
  } else if (nrow(tempDat) == 0){
    main_df$incong_error_ITPS[rr] <- NA
    main_df$incong_correct_ITPS[rr] <- NA
    main_df$ITPS_difference_score[rr] <- NA
  }
}
##########################################################################################################################
#################### Theta MFC
### Loading EEG Theta power data
eeg_theta_power_mfc250 <- read.csv(file = "/Users/kihossei/Documents/GitHub/memory-for-error-mini/derivatives/eeg/TF_outputs/csv_for_stat/theta/MFC/250/theta_power.csv")

# Keeping the columns that we need!
eeg_theta_power_mfc250 <- eeg_theta_power_mfc250[c("id", "incong_error_theta_power", "incong_correct_theta_power", "difference_score")]

# adding new columns to the "main_df" dataframe from eeg_erp
for (rr in 1:nrow(main_df)){
  temp_id <- main_df$participant_id[rr]
  tempDat <- filter(eeg_theta_power_mfc250, id == temp_id)
  if (nrow(tempDat) == 1){
    main_df$incong_error_theta_power_mfc250[rr] <- tempDat$incong_error_theta_power
    main_df$incong_correct_theta_power_mfc250[rr] <- tempDat$incong_correct_theta_power
    main_df$theta_power_mfc250_difference_score[rr] <- tempDat$difference_score
  } else if (nrow(tempDat) == 0){
    main_df$incong_error_theta_power_mfc250[rr] <- NA
    main_df$incong_correct_theta_power_mfc250[rr] <- NA
    main_df$theta_power_mfc250_difference_score[rr] <- NA
  }
}

### Loading EEG Theta power data
eeg_theta_power_mfc500 <- read.csv(file = "/Users/kihossei/Documents/GitHub/memory-for-error-mini/derivatives/eeg/TF_outputs/csv_for_stat/theta/MFC/500/theta_power.csv")

# Keeping the columns that we need!
eeg_theta_power_mfc500 <- eeg_theta_power_mfc500[c("id", "incong_error_theta_power", "incong_correct_theta_power", "difference_score")]

# adding new columns to the "main_df" dataframe from eeg_erp
for (rr in 1:nrow(main_df)){
  temp_id <- main_df$participant_id[rr]
  tempDat <- filter(eeg_theta_power_mfc500, id == temp_id)
  if (nrow(tempDat) == 1){
    main_df$incong_error_theta_power_mfc500[rr] <- tempDat$incong_error_theta_power
    main_df$incong_correct_theta_power_mfc500[rr] <- tempDat$incong_correct_theta_power
    main_df$theta_power_mfc500_difference_score[rr] <- tempDat$difference_score
  } else if (nrow(tempDat) == 0){
    main_df$incong_error_theta_power_mfc500[rr] <- NA
    main_df$incong_correct_theta_power_mfc500[rr] <- NA
    main_df$theta_power_mfc500_difference_score[rr] <- NA
  }
}

### Loading EEG ITPS data
eeg_theta_ITPS_mfc250 <- read.csv(file = "/Users/kihossei/Documents/GitHub/memory-for-error-mini/derivatives/eeg/TF_outputs/csv_for_stat/theta/MFC/250/ITPS.csv")

# Keeping the columns that we need!
eeg_theta_ITPS_mfc250 <- eeg_theta_ITPS_mfc250[c("id", "incong_error_ITPS", "incong_correct_ITPS", "difference_score")]

# adding new columns to the "main_df" dataframe from eeg_erp
for (rr in 1:nrow(main_df)){
  temp_id <- main_df$participant_id[rr]
  tempDat <- filter(eeg_theta_ITPS_mfc250, id == temp_id)
  if (nrow(tempDat) == 1){
    main_df$incong_error_theta_ITPS_mfc250[rr] <- tempDat$incong_error_ITPS
    main_df$incong_correct_theta_ITPS_mfc250[rr] <- tempDat$incong_correct_ITPS
    main_df$theta_ITPS_mfc250_difference_score[rr] <- tempDat$difference_score
  } else if (nrow(tempDat) == 0){
    main_df$incong_error_theta_ITPS_mfc250[rr] <- NA
    main_df$incong_correct_theta_ITPS_mfc250[rr] <- NA
    main_df$theta_ITPS_mfc250_difference_score[rr] <- NA
  }
}

### Loading EEG ITPS data
eeg_theta_ITPS_mfc500 <- read.csv(file = "/Users/kihossei/Documents/GitHub/memory-for-error-mini/derivatives/eeg/TF_outputs/csv_for_stat/theta/MFC/500/ITPS.csv")

# Keeping the columns that we need!
eeg_theta_ITPS_mfc500 <- eeg_theta_ITPS_mfc500[c("id", "incong_error_ITPS", "incong_correct_ITPS", "difference_score")]

# adding new columns to the "main_df" dataframe from eeg_erp
for (rr in 1:nrow(main_df)){
  temp_id <- main_df$participant_id[rr]
  tempDat <- filter(eeg_theta_ITPS_mfc500, id == temp_id)
  if (nrow(tempDat) == 1){
    main_df$incong_error_theta_ITPS_mfc500[rr] <- tempDat$incong_error_ITPS
    main_df$incong_correct_theta_ITPS_mfc500[rr] <- tempDat$incong_correct_ITPS
    main_df$theta_ITPS_mfc500_difference_score[rr] <- tempDat$difference_score
  } else if (nrow(tempDat) == 0){
    main_df$incong_error_theta_ITPS_mfc500[rr] <- NA
    main_df$incong_correct_theta_ITPS_mfc500[rr] <- NA
    main_df$theta_ITPS_mfc500_difference_score[rr] <- NA
  }
}

#################### Theta Posterior
### Loading EEG Theta power data
eeg_theta_power_posterior250 <- read.csv(file = "/Users/kihossei/Documents/GitHub/memory-for-error-mini/derivatives/eeg/TF_outputs/csv_for_stat/theta/posterior/250/theta_power.csv")

# Keeping the columns that we need!
eeg_theta_power_posterior250 <- eeg_theta_power_posterior250[c("id", "incong_error_theta_power", "incong_correct_theta_power", "difference_score")]

# adding new columns to the "main_df" dataframe from eeg_erp
for (rr in 1:nrow(main_df)){
  temp_id <- main_df$participant_id[rr]
  tempDat <- filter(eeg_theta_power_posterior250, id == temp_id)
  if (nrow(tempDat) == 1){
    main_df$incong_error_theta_power_posterior250[rr] <- tempDat$incong_error_theta_power
    main_df$incong_correct_theta_power_posterior250[rr] <- tempDat$incong_correct_theta_power
    main_df$theta_power_posterior250_difference_score[rr] <- tempDat$difference_score
  } else if (nrow(tempDat) == 0){
    main_df$incong_error_theta_power_posterior250[rr] <- NA
    main_df$incong_correct_theta_power_posterior250[rr] <- NA
    main_df$theta_power_posterior250_difference_score[rr] <- NA
  }
}

### Loading EEG Theta power data
eeg_theta_power_posterior500 <- read.csv(file = "/Users/kihossei/Documents/GitHub/memory-for-error-mini/derivatives/eeg/TF_outputs/csv_for_stat/theta/posterior/500/theta_power.csv")

# Keeping the columns that we need!
eeg_theta_power_posterior500 <- eeg_theta_power_posterior500[c("id", "incong_error_theta_power", "incong_correct_theta_power", "difference_score")]

# adding new columns to the "main_df" dataframe from eeg_erp
for (rr in 1:nrow(main_df)){
  temp_id <- main_df$participant_id[rr]
  tempDat <- filter(eeg_theta_power_posterior500, id == temp_id)
  if (nrow(tempDat) == 1){
    main_df$incong_error_theta_power_posterior500[rr] <- tempDat$incong_error_theta_power
    main_df$incong_correct_theta_power_posterior500[rr] <- tempDat$incong_correct_theta_power
    main_df$theta_power_posterior500_difference_score[rr] <- tempDat$difference_score
  } else if (nrow(tempDat) == 0){
    main_df$incong_error_theta_power_posterior500[rr] <- NA
    main_df$incong_correct_theta_power_posterior500[rr] <- NA
    main_df$theta_power_posterior500_difference_score[rr] <- NA
  }
}

### Loading EEG ITPS data
eeg_theta_ITPS_posterior250 <- read.csv(file = "/Users/kihossei/Documents/GitHub/memory-for-error-mini/derivatives/eeg/TF_outputs/csv_for_stat/theta/posterior/250/ITPS.csv")

# Keeping the columns that we need!
eeg_theta_ITPS_posterior250 <- eeg_theta_ITPS_posterior250[c("id", "incong_error_ITPS", "incong_correct_ITPS", "difference_score")]

# adding new columns to the "main_df" dataframe from eeg_erp
for (rr in 1:nrow(main_df)){
  temp_id <- main_df$participant_id[rr]
  tempDat <- filter(eeg_theta_ITPS_posterior250, id == temp_id)
  if (nrow(tempDat) == 1){
    main_df$incong_error_theta_ITPS_posterior250[rr] <- tempDat$incong_error_ITPS
    main_df$incong_correct_theta_ITPS_posterior250[rr] <- tempDat$incong_correct_ITPS
    main_df$theta_ITPS_posterior250_difference_score[rr] <- tempDat$difference_score
  } else if (nrow(tempDat) == 0){
    main_df$incong_error_theta_ITPS_posterior250[rr] <- NA
    main_df$incong_correct_theta_ITPS_posterior250[rr] <- NA
    main_df$theta_ITPS_posterior250_difference_score[rr] <- NA
  }
}

### Loading EEG ITPS data
eeg_theta_ITPS_posterior500 <- read.csv(file = "/Users/kihossei/Documents/GitHub/memory-for-error-mini/derivatives/eeg/TF_outputs/csv_for_stat/theta/posterior/500/ITPS.csv")

# Keeping the columns that we need!
eeg_theta_ITPS_posterior500 <- eeg_theta_ITPS_posterior500[c("id", "incong_error_ITPS", "incong_correct_ITPS", "difference_score")]

# adding new columns to the "main_df" dataframe from eeg_erp
for (rr in 1:nrow(main_df)){
  temp_id <- main_df$participant_id[rr]
  tempDat <- filter(eeg_theta_ITPS_posterior500, id == temp_id)
  if (nrow(tempDat) == 1){
    main_df$incong_error_theta_ITPS_posterior500[rr] <- tempDat$incong_error_ITPS
    main_df$incong_correct_theta_ITPS_posterior500[rr] <- tempDat$incong_correct_ITPS
    main_df$theta_ITPS_posterior500_difference_score[rr] <- tempDat$difference_score
  } else if (nrow(tempDat) == 0){
    main_df$incong_error_theta_ITPS_posterior500[rr] <- NA
    main_df$incong_correct_theta_ITPS_posterior500[rr] <- NA
    main_df$theta_ITPS_posterior500_difference_score[rr] <- NA
  }
}

#####################################################################################################
#################### alpha MFC
### Loading EEG alpha power data
eeg_alpha_power_mfc250 <- read.csv(file = "/Users/kihossei/Documents/GitHub/memory-for-error-mini/derivatives/eeg/TF_outputs/csv_for_stat/alpha/MFC/250/theta_power.csv")

# Keeping the columns that we need!
eeg_alpha_power_mfc250 <- eeg_alpha_power_mfc250[c("id", "incong_error_theta_power", "incong_correct_theta_power", "difference_score")]

# adding new columns to the "main_df" dataframe from eeg_erp
for (rr in 1:nrow(main_df)){
  temp_id <- main_df$participant_id[rr]
  tempDat <- filter(eeg_alpha_power_mfc250, id == temp_id)
  if (nrow(tempDat) == 1){
    main_df$incong_error_alpha_power_mfc250[rr] <- tempDat$incong_error_theta_power
    main_df$incong_correct_alpha_power_mfc250[rr] <- tempDat$incong_correct_theta_power
    main_df$alpha_power_mfc250_difference_score[rr] <- tempDat$difference_score
  } else if (nrow(tempDat) == 0){
    main_df$incong_error_alpha_power_mfc250[rr] <- NA
    main_df$incong_correct_alpha_power_mfc250[rr] <- NA
    main_df$alpha_power_mfc250_difference_score[rr] <- NA
  }
}

### Loading EEG alpha power data
eeg_alpha_power_mfc500 <- read.csv(file = "/Users/kihossei/Documents/GitHub/memory-for-error-mini/derivatives/eeg/TF_outputs/csv_for_stat/alpha/MFC/500/theta_power.csv")

# Keeping the columns that we need!
eeg_alpha_power_mfc500 <- eeg_alpha_power_mfc500[c("id", "incong_error_theta_power", "incong_correct_theta_power", "difference_score")]

# adding new columns to the "main_df" dataframe from eeg_erp
for (rr in 1:nrow(main_df)){
  temp_id <- main_df$participant_id[rr]
  tempDat <- filter(eeg_alpha_power_mfc500, id == temp_id)
  if (nrow(tempDat) == 1){
    main_df$incong_error_alpha_power_mfc500[rr] <- tempDat$incong_error_theta_power
    main_df$incong_correct_alpha_power_mfc500[rr] <- tempDat$incong_correct_theta_power
    main_df$alpha_power_mfc500_difference_score[rr] <- tempDat$difference_score
  } else if (nrow(tempDat) == 0){
    main_df$incong_error_alpha_power_mfc500[rr] <- NA
    main_df$incong_correct_alpha_power_mfc500[rr] <- NA
    main_df$alpha_power_mfc500_difference_score[rr] <- NA
  }
}

### Loading EEG ITPS data
eeg_alpha_ITPS_mfc250 <- read.csv(file = "/Users/kihossei/Documents/GitHub/memory-for-error-mini/derivatives/eeg/TF_outputs/csv_for_stat/alpha/MFC/250/ITPS.csv")

# Keeping the columns that we need!
eeg_alpha_ITPS_mfc250 <- eeg_alpha_ITPS_mfc250[c("id", "incong_error_ITPS", "incong_correct_ITPS", "difference_score")]

# adding new columns to the "main_df" dataframe from eeg_erp
for (rr in 1:nrow(main_df)){
  temp_id <- main_df$participant_id[rr]
  tempDat <- filter(eeg_alpha_ITPS_mfc250, id == temp_id)
  if (nrow(tempDat) == 1){
    main_df$incong_error_alpha_ITPS_mfc250[rr] <- tempDat$incong_error_ITPS
    main_df$incong_correct_alpha_ITPS_mfc250[rr] <- tempDat$incong_correct_ITPS
    main_df$alpha_ITPS_mfc250_difference_score[rr] <- tempDat$difference_score
  } else if (nrow(tempDat) == 0){
    main_df$incong_error_alpha_ITPS_mfc250[rr] <- NA
    main_df$incong_correct_alpha_ITPS_mfc250[rr] <- NA
    main_df$alpha_ITPS_mfc250_difference_score[rr] <- NA
  }
}

### Loading EEG ITPS data
eeg_alpha_ITPS_mfc500 <- read.csv(file = "/Users/kihossei/Documents/GitHub/memory-for-error-mini/derivatives/eeg/TF_outputs/csv_for_stat/alpha/MFC/500/ITPS.csv")

# Keeping the columns that we need!
eeg_alpha_ITPS_mfc500 <- eeg_alpha_ITPS_mfc500[c("id", "incong_error_ITPS", "incong_correct_ITPS", "difference_score")]

# adding new columns to the "main_df" dataframe from eeg_erp
for (rr in 1:nrow(main_df)){
  temp_id <- main_df$participant_id[rr]
  tempDat <- filter(eeg_alpha_ITPS_mfc500, id == temp_id)
  if (nrow(tempDat) == 1){
    main_df$incong_error_alpha_ITPS_mfc500[rr] <- tempDat$incong_error_ITPS
    main_df$incong_correct_alpha_ITPS_mfc500[rr] <- tempDat$incong_correct_ITPS
    main_df$alpha_ITPS_mfc500_difference_score[rr] <- tempDat$difference_score
  } else if (nrow(tempDat) == 0){
    main_df$incong_error_alpha_ITPS_mfc500[rr] <- NA
    main_df$incong_correct_alpha_ITPS_mfc500[rr] <- NA
    main_df$alpha_ITPS_mfc500_difference_score[rr] <- NA
  }
}

#################### alpha Posterior
### Loading EEG alpha power data
eeg_alpha_power_posterior250 <- read.csv(file = "/Users/kihossei/Documents/GitHub/memory-for-error-mini/derivatives/eeg/TF_outputs/csv_for_stat/alpha/posterior/250/theta_power.csv")

# Keeping the columns that we need!
eeg_alpha_power_posterior250 <- eeg_alpha_power_posterior250[c("id", "incong_error_theta_power", "incong_correct_theta_power", "difference_score")]

# adding new columns to the "main_df" dataframe from eeg_erp
for (rr in 1:nrow(main_df)){
  temp_id <- main_df$participant_id[rr]
  tempDat <- filter(eeg_alpha_power_posterior250, id == temp_id)
  if (nrow(tempDat) == 1){
    main_df$incong_error_alpha_power_posterior250[rr] <- tempDat$incong_error_theta_power
    main_df$incong_correct_alpha_power_posterior250[rr] <- tempDat$incong_correct_theta_power
    main_df$alpha_power_posterior250_difference_score[rr] <- tempDat$difference_score
  } else if (nrow(tempDat) == 0){
    main_df$incong_error_alpha_power_posterior250[rr] <- NA
    main_df$incong_correct_alpha_power_posterior250[rr] <- NA
    main_df$alpha_power_posterior250_difference_score[rr] <- NA
  }
}

### Loading EEG alpha power data
eeg_alpha_power_posterior500 <- read.csv(file = "/Users/kihossei/Documents/GitHub/memory-for-error-mini/derivatives/eeg/TF_outputs/csv_for_stat/alpha/posterior/500/theta_power.csv")

# Keeping the columns that we need!
eeg_alpha_power_posterior500 <- eeg_alpha_power_posterior500[c("id", "incong_error_theta_power", "incong_correct_theta_power", "difference_score")]

# adding new columns to the "main_df" dataframe from eeg_erp
for (rr in 1:nrow(main_df)){
  temp_id <- main_df$participant_id[rr]
  tempDat <- filter(eeg_alpha_power_posterior500, id == temp_id)
  if (nrow(tempDat) == 1){
    main_df$incong_error_alpha_power_posterior500[rr] <- tempDat$incong_error_theta_power
    main_df$incong_correct_alpha_power_posterior500[rr] <- tempDat$incong_correct_theta_power
    main_df$alpha_power_posterior500_difference_score[rr] <- tempDat$difference_score
  } else if (nrow(tempDat) == 0){
    main_df$incong_error_alpha_power_posterior500[rr] <- NA
    main_df$incong_correct_alpha_power_posterior500[rr] <- NA
    main_df$alpha_power_posterior500_difference_score[rr] <- NA
  }
}

### Loading EEG ITPS data
eeg_alpha_ITPS_posterior250 <- read.csv(file = "/Users/kihossei/Documents/GitHub/memory-for-error-mini/derivatives/eeg/TF_outputs/csv_for_stat/alpha/posterior/250/ITPS.csv")

# Keeping the columns that we need!
eeg_alpha_ITPS_posterior250 <- eeg_alpha_ITPS_posterior250[c("id", "incong_error_ITPS", "incong_correct_ITPS", "difference_score")]

# adding new columns to the "main_df" dataframe from eeg_erp
for (rr in 1:nrow(main_df)){
  temp_id <- main_df$participant_id[rr]
  tempDat <- filter(eeg_alpha_ITPS_posterior250, id == temp_id)
  if (nrow(tempDat) == 1){
    main_df$incong_error_alpha_ITPS_posterior250[rr] <- tempDat$incong_error_ITPS
    main_df$incong_correct_alpha_ITPS_posterior250[rr] <- tempDat$incong_correct_ITPS
    main_df$alpha_ITPS_posterior250_difference_score[rr] <- tempDat$difference_score
  } else if (nrow(tempDat) == 0){
    main_df$incong_error_alpha_ITPS_posterior250[rr] <- NA
    main_df$incong_correct_alpha_ITPS_posterior250[rr] <- NA
    main_df$alpha_ITPS_posterior250_difference_score[rr] <- NA
  }
}

### Loading EEG ITPS data
eeg_alpha_ITPS_posterior500 <- read.csv(file = "/Users/kihossei/Documents/GitHub/memory-for-error-mini/derivatives/eeg/TF_outputs/csv_for_stat/alpha/posterior/500/ITPS.csv")

# Keeping the columns that we need!
eeg_alpha_ITPS_posterior500 <- eeg_alpha_ITPS_posterior500[c("id", "incong_error_ITPS", "incong_correct_ITPS", "difference_score")]

# adding new columns to the "main_df" dataframe from eeg_erp
for (rr in 1:nrow(main_df)){
  temp_id <- main_df$participant_id[rr]
  tempDat <- filter(eeg_alpha_ITPS_posterior500, id == temp_id)
  if (nrow(tempDat) == 1){
    main_df$incong_error_alpha_ITPS_posterior500[rr] <- tempDat$incong_error_ITPS
    main_df$incong_correct_alpha_ITPS_posterior500[rr] <- tempDat$incong_correct_ITPS
    main_df$alpha_ITPS_posterior500_difference_score[rr] <- tempDat$difference_score
  } else if (nrow(tempDat) == 0){
    main_df$incong_error_alpha_ITPS_posterior500[rr] <- NA
    main_df$incong_correct_alpha_ITPS_posterior500[rr] <- NA
    main_df$alpha_ITPS_posterior500_difference_score[rr] <- NA
  }
}


### Loading EEG wPLI data
eeg_theta_wPLI_latfrontal250 <- read.csv(file = "/Users/kihossei/Documents/GitHub/memory-for-error-mini/derivatives/eeg/TF_outputs/csv_for_stat/theta/wPLI/MFC/wPLI.csv")

# Keeping the columns that we need!
eeg_theta_wPLI_latfrontal250 <- eeg_theta_wPLI_latfrontal250[c("id", "incong_error_wPLI", "incong_correct_wPLI", "difference_score")]

# adding new columns to the "main_df" dataframe from eeg_erp
for (rr in 1:nrow(main_df)){
  temp_id <- main_df$participant_id[rr]
  tempDat <- filter(eeg_theta_wPLI_latfrontal250, id == temp_id)
  if (nrow(tempDat) == 1){
    main_df$incong_error_theta_wPLI_latfrontal250[rr] <- tempDat$incong_error_wPLI
    main_df$incong_correct_theta_wPLI_latfrontal250[rr] <- tempDat$incong_correct_wPLI
    main_df$theta_wPLI_latfrontal250_difference_score[rr] <- tempDat$difference_score
  } else if (nrow(tempDat) == 0){
    main_df$incong_error_theta_wPLI_latfrontal250[rr] <- NA
    main_df$incong_correct_theta_wPLI_latfrontal250[rr] <- NA
    main_df$theta_wPLI_latfrontal250_difference_score[rr] <- NA
  }
}

### Loading EEG wPLI data
eeg_alpha_wPLI_latfrontal250 <- read.csv(file = "/Users/kihossei/Documents/GitHub/memory-for-error-mini/derivatives/eeg/TF_outputs/csv_for_stat/alpha/wPLI/MFC/wPLI.csv")

# Keeping the columns that we need!
eeg_alpha_wPLI_latfrontal250 <- eeg_alpha_wPLI_latfrontal250[c("id", "incong_error_wPLI", "incong_correct_wPLI", "difference_score")]

# adding new columns to the "main_df" dataframe from eeg_erp
for (rr in 1:nrow(main_df)){
  temp_id <- main_df$participant_id[rr]
  tempDat <- filter(eeg_alpha_wPLI_latfrontal250, id == temp_id)
  if (nrow(tempDat) == 1){
    main_df$incong_error_alpha_wPLI_latfrontal250[rr] <- tempDat$incong_error_wPLI
    main_df$incong_correct_alpha_wPLI_latfrontal250[rr] <- tempDat$incong_correct_wPLI
    main_df$alpha_wPLI_latfrontal250_difference_score[rr] <- tempDat$difference_score
  } else if (nrow(tempDat) == 0){
    main_df$incong_error_alpha_wPLI_latfrontal250[rr] <- NA
    main_df$incong_correct_alpha_wPLI_latfrontal250[rr] <- NA
    main_df$alpha_wPLI_latfrontal250_difference_score[rr] <- NA
  }
}

### Loading EEG wPLI data
eeg_theta_wPLI_posterior250 <- read.csv(file = "/Users/kihossei/Documents/GitHub/memory-for-error-mini/derivatives/eeg/TF_outputs/csv_for_stat/theta/wPLI/posterior/wPLI.csv")

# Keeping the columns that we need!
eeg_theta_wPLI_posterior250 <- eeg_theta_wPLI_posterior250[c("id", "incong_error_wPLI", "incong_correct_wPLI", "difference_score")]

# adding new columns to the "main_df" dataframe from eeg_erp
for (rr in 1:nrow(main_df)){
  temp_id <- main_df$participant_id[rr]
  tempDat <- filter(eeg_theta_wPLI_posterior250, id == temp_id)
  if (nrow(tempDat) == 1){
    main_df$incong_error_theta_wPLI_posterior250[rr] <- tempDat$incong_error_wPLI
    main_df$incong_correct_theta_wPLI_posterior250[rr] <- tempDat$incong_correct_wPLI
    main_df$theta_wPLI_posterior250_difference_score[rr] <- tempDat$difference_score
  } else if (nrow(tempDat) == 0){
    main_df$incong_error_theta_wPLI_posterior250[rr] <- NA
    main_df$incong_correct_theta_wPLI_posterior250[rr] <- NA
    main_df$theta_wPLI_posterior250_difference_score[rr] <- NA
  }
}

### Loading EEG wPLI data
eeg_alpha_wPLI_posterior250 <- read.csv(file = "/Users/kihossei/Documents/GitHub/memory-for-error-mini/derivatives/eeg/TF_outputs/csv_for_stat/alpha/wPLI/posterior/wPLI.csv")

# Keeping the columns that we need!
eeg_alpha_wPLI_posterior250 <- eeg_alpha_wPLI_posterior250[c("id", "incong_error_wPLI", "incong_correct_wPLI", "difference_score")]

# adding new columns to the "main_df" dataframe from eeg_erp
for (rr in 1:nrow(main_df)){
  temp_id <- main_df$participant_id[rr]
  tempDat <- filter(eeg_alpha_wPLI_posterior250, id == temp_id)
  if (nrow(tempDat) == 1){
    main_df$incong_error_alpha_wPLI_posterior250[rr] <- tempDat$incong_error_wPLI
    main_df$incong_correct_alpha_wPLI_posterior250[rr] <- tempDat$incong_correct_wPLI
    main_df$alpha_wPLI_posterior250_difference_score[rr] <- tempDat$difference_score
  } else if (nrow(tempDat) == 0){
    main_df$incong_error_alpha_wPLI_posterior250[rr] <- NA
    main_df$incong_correct_alpha_wPLI_posterior250[rr] <- NA
    main_df$alpha_wPLI_posterior250_difference_score[rr] <- NA
  }
}

#### Exploratory ones
### Loading EEG wPLI data
eeg_theta_wPLI_21_25_250 <- read.csv(file = "/Users/kihossei/Documents/GitHub/memory-for-error-mini/derivatives/eeg/TF_outputs/csv_for_stat/theta/wPLI/21_25/wPLI.csv")

# Keeping the columns that we need!
eeg_theta_wPLI_21_25_250 <- eeg_theta_wPLI_21_25_250[c("id", "incong_error_wPLI", "incong_correct_wPLI", "difference_score")]

# adding new columns to the "main_df" dataframe from eeg_erp
for (rr in 1:nrow(main_df)){
  temp_id <- main_df$participant_id[rr]
  tempDat <- filter(eeg_theta_wPLI_21_25_250, id == temp_id)
  if (nrow(tempDat) == 1){
    main_df$incong_error_theta_wPLI_21_25_250[rr] <- tempDat$incong_error_wPLI
    main_df$incong_correct_theta_wPLI_21_25_250[rr] <- tempDat$incong_correct_wPLI
    main_df$theta_wPLI_21_25_250_difference_score[rr] <- tempDat$difference_score
  } else if (nrow(tempDat) == 0){
    main_df$incong_error_theta_wPLI_21_25_250[rr] <- NA
    main_df$incong_correct_theta_wPLI_21_25_250[rr] <- NA
    main_df$theta_wPLI_21_25_250_difference_score[rr] <- NA
  }
}

### Loading EEG theta power data
eeg_theta_power_3_18_20_250 <- read.csv(file = "/Users/kihossei/Documents/GitHub/memory-for-error-mini/derivatives/eeg/TF_outputs/csv_for_stat/theta/3_18_20/250/theta_power.csv")

# Keeping the columns that we need!
eeg_theta_power_3_18_20_250 <- eeg_theta_power_3_18_20_250[c("id", "incong_error_theta_power", "incong_correct_theta_power", "difference_score")]

# adding new columns to the "main_df" dataframe from eeg_erp
for (rr in 1:nrow(main_df)){
  temp_id <- main_df$participant_id[rr]
  tempDat <- filter(eeg_theta_power_3_18_20_250, id == temp_id)
  if (nrow(tempDat) == 1){
    main_df$incong_error_theta_power_3_18_20_250[rr] <- tempDat$incong_error_theta_power
    main_df$incong_correct_theta_power_3_18_20_250[rr] <- tempDat$incong_correct_theta_power
    main_df$theta_power_3_18_20_250_difference_score[rr] <- tempDat$difference_score
  } else if (nrow(tempDat) == 0){
    main_df$incong_error_theta_power_3_18_20_250[rr] <- NA
    main_df$incong_correct_theta_power_3_18_20_250[rr] <- NA
    main_df$theta_power_3_18_20_250_difference_score[rr] <- NA
  }
}

### Loading EEG theta itps data
eeg_theta_itps_3_18_20_250 <- read.csv(file = "/Users/kihossei/Documents/GitHub/memory-for-error-mini/derivatives/eeg/TF_outputs/csv_for_stat/theta/3_18_20/250/ITPS.csv")

# Keeping the columns that we need!
eeg_theta_itps_3_18_20_250 <- eeg_theta_itps_3_18_20_250[c("id", "incong_error_ITPS", "incong_correct_ITPS", "difference_score")]

# adding new columns to the "main_df" dataframe from eeg_erp
for (rr in 1:nrow(main_df)){
  temp_id <- main_df$participant_id[rr]
  tempDat <- filter(eeg_theta_itps_3_18_20_250, id == temp_id)
  if (nrow(tempDat) == 1){
    main_df$incong_error_theta_itps_3_18_20_250[rr] <- tempDat$incong_error_ITPS
    main_df$incong_correct_theta_itps_3_18_20_250[rr] <- tempDat$incong_correct_ITPS
    main_df$theta_itps_3_18_20_250_difference_score[rr] <- tempDat$difference_score
  } else if (nrow(tempDat) == 0){
    main_df$incong_error_theta_itps_3_18_20_250[rr] <- NA
    main_df$incong_correct_theta_itps_3_18_20_250[rr] <- NA
    main_df$theta_itps_3_18_20_250_difference_score[rr] <- NA
  }
}

####################################################################
# Removing outliers for variables of interest
# list of variables of interest: memoryBias_score, d_prime_error, d_prime_correct, post_d_prime_error, post_d_prime_correct, scaared_b_scrdSoc_s1_r1_e1, scaared_b_scrdTotal_s1_r1_e1, scaared_b_scrdGA_s1_r1_e1, d_prime_error_minus_correct ,post_d_prime_error_minus_correct, unfriendly_error_minus_correct, unfriendly_post_error_minus_correct!
mean_memoryBias_score <- mean(as.numeric(main_df$memoryBias_score), na.rm = TRUE)
sd_memoryBias_score_threeTimes <- 3*sd(as.numeric(main_df$memoryBias_score), na.rm = TRUE)

for (zesht4 in 1:nrow(main_df)){
  if (!is.na(as.numeric(main_df$memoryBias_score[zesht4])) && !is.na(as.numeric(main_df$percent_post_errorFaces_reported_friendly[zesht4])) && !is.na(as.numeric(main_df$percent_post_correctFaces_reported_friendly[zesht4])) && !is.na(as.numeric(main_df$percent_pre_errorFaces_reported_friendly[zesht4])) && !is.na(as.numeric(main_df$percent_pre_correctFaces_reported_friendly[zesht4])) && !is.na(as.numeric(main_df$percent_incong_correctFaces_reported_friendly[zesht4])) && !is.na(as.numeric(main_df$percent_incong_errorFaces_reported_friendly[zesht4])) && !is.na(as.numeric(main_df$scaared_b_scrdSoc_s1_r1_e1[zesht4])) && !is.na(as.numeric(main_df$scaared_b_scrdTotal_s1_r1_e1[zesht4])) && !is.na(as.numeric(main_df$scaared_b_scrdGA_s1_r1_e1[zesht4]))  && !is.na(as.numeric(main_df$bfne_b_scrdTotal_s1_r1_e1[zesht4]))){
    if (as.numeric(main_df$memoryBias_score[zesht4]) >= (mean_memoryBias_score - sd_memoryBias_score_threeTimes) && as.numeric(main_df$memoryBias_score[zesht4]) <= (mean_memoryBias_score + sd_memoryBias_score_threeTimes)){
      main_df$memoryBias_score[zesht4] <- as.numeric(main_df$memoryBias_score[zesht4])
    } else {
      main_df$memoryBias_score[zesht4] <- NA
    }

    if (as.numeric(main_df$percent_post_errorFaces_reported_friendly[zesht4]) >= (mean(as.numeric(main_df$percent_post_errorFaces_reported_friendly), na.rm = TRUE) - (3*sd(as.numeric(main_df$percent_post_errorFaces_reported_friendly), na.rm = TRUE))) && as.numeric(main_df$percent_post_errorFaces_reported_friendly[zesht4]) <= (mean(as.numeric(main_df$percent_post_errorFaces_reported_friendly), na.rm = TRUE) + (3*sd(as.numeric(main_df$percent_post_errorFaces_reported_friendly), na.rm = TRUE)))){
      main_df$percent_post_errorFaces_reported_friendly[zesht4] <- as.numeric(main_df$percent_post_errorFaces_reported_friendly[zesht4])
    } else {
      main_df$percent_post_errorFaces_reported_friendly[zesht4] <- NA
    }

    if (as.numeric(main_df$percent_post_correctFaces_reported_friendly[zesht4]) >= (mean(as.numeric(main_df$percent_post_correctFaces_reported_friendly), na.rm = TRUE) - (3*sd(as.numeric(main_df$percent_post_correctFaces_reported_friendly), na.rm = TRUE))) && as.numeric(main_df$percent_post_correctFaces_reported_friendly[zesht4]) <= (mean(as.numeric(main_df$percent_post_correctFaces_reported_friendly), na.rm = TRUE) + (3*sd(as.numeric(main_df$percent_post_correctFaces_reported_friendly), na.rm = TRUE)))){
      main_df$percent_post_correctFaces_reported_friendly[zesht4] <- as.numeric(main_df$percent_post_correctFaces_reported_friendly[zesht4])
    } else {
      main_df$percent_post_correctFaces_reported_friendly[zesht4] <- NA
    }

    if (as.numeric(main_df$percent_pre_errorFaces_reported_friendly[zesht4]) >= (mean(as.numeric(main_df$percent_pre_errorFaces_reported_friendly), na.rm = TRUE) - (3*sd(as.numeric(main_df$percent_pre_errorFaces_reported_friendly), na.rm = TRUE))) && as.numeric(main_df$percent_pre_errorFaces_reported_friendly[zesht4]) <= (mean(as.numeric(main_df$percent_pre_errorFaces_reported_friendly), na.rm = TRUE) + (3*sd(as.numeric(main_df$percent_pre_errorFaces_reported_friendly), na.rm = TRUE)))){
      main_df$percent_pre_errorFaces_reported_friendly[zesht4] <- as.numeric(main_df$percent_pre_errorFaces_reported_friendly[zesht4])
    } else {
      main_df$percent_pre_errorFaces_reported_friendly[zesht4] <- NA
    }

    if (as.numeric(main_df$percent_pre_correctFaces_reported_friendly[zesht4]) >= (mean(as.numeric(main_df$percent_pre_correctFaces_reported_friendly), na.rm = TRUE) - (3*sd(as.numeric(main_df$percent_pre_correctFaces_reported_friendly), na.rm = TRUE))) && as.numeric(main_df$percent_pre_correctFaces_reported_friendly[zesht4]) <= (mean(as.numeric(main_df$percent_pre_correctFaces_reported_friendly), na.rm = TRUE) + (3*sd(as.numeric(main_df$percent_pre_correctFaces_reported_friendly), na.rm = TRUE)))){
      main_df$percent_pre_correctFaces_reported_friendly[zesht4] <- as.numeric(main_df$percent_pre_correctFaces_reported_friendly[zesht4])
    } else {
      main_df$percent_pre_correctFaces_reported_friendly[zesht4] <- NA
    }

    if (as.numeric(main_df$scaared_b_scrdSoc_s1_r1_e1[zesht4]) >= (mean(as.numeric(main_df$scaared_b_scrdSoc_s1_r1_e1), na.rm = TRUE) - (3*sd(as.numeric(main_df$scaared_b_scrdSoc_s1_r1_e1), na.rm = TRUE))) && as.numeric(main_df$scaared_b_scrdSoc_s1_r1_e1[zesht4]) <= (mean(as.numeric(main_df$scaared_b_scrdSoc_s1_r1_e1), na.rm = TRUE) + (3*sd(as.numeric(main_df$scaared_b_scrdSoc_s1_r1_e1), na.rm = TRUE)))){
      main_df$scaared_b_scrdSoc_s1_r1_e1[zesht4] <- as.numeric(main_df$scaared_b_scrdSoc_s1_r1_e1[zesht4])
    } else {
      main_df$scaared_b_scrdSoc_s1_r1_e1[zesht4] <- NA
    }

    if (as.numeric(main_df$scaared_b_scrdTotal_s1_r1_e1[zesht4]) >= (mean(as.numeric(main_df$scaared_b_scrdTotal_s1_r1_e1), na.rm = TRUE) - (3*sd(as.numeric(main_df$scaared_b_scrdTotal_s1_r1_e1), na.rm = TRUE))) && as.numeric(main_df$scaared_b_scrdTotal_s1_r1_e1[zesht4]) <= (mean(as.numeric(main_df$scaared_b_scrdTotal_s1_r1_e1), na.rm = TRUE) + (3*sd(as.numeric(main_df$scaared_b_scrdTotal_s1_r1_e1), na.rm = TRUE)))){
      main_df$scaared_b_scrdTotal_s1_r1_e1[zesht4] <- as.numeric(main_df$scaared_b_scrdTotal_s1_r1_e1[zesht4])
    } else {
      main_df$scaared_b_scrdTotal_s1_r1_e1[zesht4] <- NA
    }

    if (as.numeric(main_df$scaared_b_scrdGA_s1_r1_e1[zesht4]) >= (mean(as.numeric(main_df$scaared_b_scrdGA_s1_r1_e1), na.rm = TRUE) - (3*sd(as.numeric(main_df$scaared_b_scrdGA_s1_r1_e1), na.rm = TRUE))) && as.numeric(main_df$scaared_b_scrdGA_s1_r1_e1[zesht4]) <= (mean(as.numeric(main_df$scaared_b_scrdGA_s1_r1_e1), na.rm = TRUE) + (3*sd(as.numeric(main_df$scaared_b_scrdGA_s1_r1_e1), na.rm = TRUE)))){
      main_df$scaared_b_scrdGA_s1_r1_e1[zesht4] <- as.numeric(main_df$scaared_b_scrdGA_s1_r1_e1[zesht4])
    } else {
      main_df$scaared_b_scrdGA_s1_r1_e1[zesht4] <- NA
    }
    if (as.numeric(main_df$bfne_b_scrdTotal_s1_r1_e1[zesht4]) >= (mean(as.numeric(main_df$bfne_b_scrdTotal_s1_r1_e1), na.rm = TRUE) - (3*sd(as.numeric(main_df$bfne_b_scrdTotal_s1_r1_e1), na.rm = TRUE))) && as.numeric(main_df$bfne_b_scrdTotal_s1_r1_e1[zesht4]) <= (mean(as.numeric(main_df$bfne_b_scrdTotal_s1_r1_e1), na.rm = TRUE) + (3*sd(as.numeric(main_df$bfne_b_scrdTotal_s1_r1_e1), na.rm = TRUE)))){
      main_df$bfne_b_scrdTotal_s1_r1_e1[zesht4] <- as.numeric(main_df$bfne_b_scrdTotal_s1_r1_e1[zesht4])
    } else {
      main_df$bfne_b_scrdTotal_s1_r1_e1[zesht4] <- NA
    }
  }
}



####################
# Save the dataset
# write the extracted and computed summary scores to disk
write.csv(main_df, paste(output_path, proc_fileName, sep = "/", collapse = NULL), row.names=FALSE)
##################

